#include "hardware/flash.h"
#define FLASH_TARGET_OFFSET (1024 * 1024)

const uint8_t *flash_target_contents = (const uint8_t *) (XIP_BASE + FLASH_TARGET_OFFSET);

uint8_t data[FLASH_PAGE_SIZE] = { HID_KEY_GUI_LEFT, HID_KEY_C, HID_KEY_M, HID_KEY_D, HID_KEY_ENTER, HID_KEY_P, HID_KEY_I, HID_KEY_N, HID_KEY_G, HID_KEY_SPACE, HID_KEY_KEYPAD_8, HID_KEY_PERIOD, HID_KEY_KEYPAD_8, HID_KEY_PERIOD, HID_KEY_KEYPAD_8, HID_KEY_PERIOD, HID_KEY_KEYPAD_8, HID_KEY_ENTER, 0x00 };
flash_range_program(FLASH_TARGET_OFFSET, data, FLASH_PAGE_SIZE);

sleep_ms(10000);